### ISSUE TITLE
fastqCombinePairedEnd.py: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by amgraham07** [enormandeau/Scripts#5]
Tried using the "fastqCombinePairedEnd.py" program. I received the following error (see below). Just thought I would forward it on to you.

File "fastqCombinePairedEnd.py", line 27
    print __doc__
                        ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by enormandeau** [comment]
Thanks for the feedback. None of my scripts were tested with Python 3. I should probably make them compatible. I will do it for this one since it is highly used.

**Comment by enormandeau** [comment]
Done!
