### ISSUE TITLE
ERROR with fastqCombinePairedEnd.py

### ISSUE THREAD

**Issue by Gian77** [enormandeau/Scripts#6]
Hello,
I am trying to re-sync some illimina read files after phix filtering using your script but I am getting this error:

IOError: [Errno 2] No such file or directory: 'no_phix/T1-3-F_CGAGCGAC-TACGAGAC_L001_R1_001.fastq.gz.nophix.fastq.nophix.fastq_pairs_R1.fastq'
Traceback (most recent call last):
  File "../fastqCombinePairedEnd.py", line 97, in <module>
    with myopen(in1 + "_pairs_R1" + outSuffix, "w") as out1:
  File "../fastqCombinePairedEnd.py", line 66, in myopen
    return open(infile, mode=mode)
IOError: [Errno 2] No such file or directory: 'no_phix/T4-1-C_CGAGCGAC-ACGTCTCG_L001_R1_001.fastq.gz.nophix.fastq.nophix.fastq_pairs_R1.fastq'
Traceback (most recent call last):
  File "../fastqCombinePairedEnd.py", line 97, in <module>
    with myopen(in1 + "_pairs_R1" + outSuffix, "w") as out1:
  File "../fastqCombinePairedEnd.py", line 66, in myopen
    return open(infile, mode=mode)

Those are how the file names look like and are inside a folder called no_phix:
T1-3-F_CGAGCGAC-TACGAGAC_L001_R2_001.fastq.gz.nophix.fastq
T4-1-C_CGAGCGAC-ACGTCTCG_L001_R1_001.fastq.gz.nophix.fastq
T4-1-F_CGAGCGAC-GATCGTGT_L001_R1_001.fastq.gz.nophix.fastq
...

And this is my code:
ls no_phix/*nophix.fastq > fastq_nophix.list
cd no_phix
while read R1
do read R2
python ../fastqCombinePairedEnd.py $R1.nophix.fastq $R2.nophix.fastq
done < ../fastq_nophix.list

Thank you so much in advance,
G.

**Comment by enormandeau** [comment]
Solved by email. File name passed to the script didn't exist.
