### ISSUE TITLE
Not getting the right results?

### ISSUE THREAD

**Issue by MalikS10** [enormandeau/Scripts#7]
Hi 

My headers look like this:
@NS500278:91:HK23CBGX2:2:13212:11182:16700/1
And
@NS500278:91:HK23CBGX2:1:11101:23209:1052/2

This is how I used the script:

python ResynchroniseFastq.py BAEL_R1_Final_Header.fastq BAEL_R2_Final_Header.fastq None

but every thing seems to be going in the singles file.

Am I doing something wrong?

**Comment by MalikS10** [comment]
Sorry this is for fastqCombinePairedEnd.py.

**Comment by enormandeau** [comment]
From the look of your file, you should use "/" as the separator, not "None".

Can you try this and confirm it works?

**Comment by enormandeau** [comment]
Please re-open if you cannot solve.

**Comment by HXP2016** [comment]
I have similar problem. The headers of my sequences look like:

@M03670:6:000000000-BCN4V:1:1101:16480:1645_SUB_CMP reverse_score=80.0; status=partial; direction=reverse; tail_quality=39.0; reverse_match=ccacctatcacataatcatg; seq_length_ori=151; seq_length=121; sample=BI_0_1_1; experiment=eDNA; location=BI_0; mid_quality=38.5267175573; head_quality=33.3; avg_quality=38.2119205298; grab=BI_0_1; reverse_primer=ccacctatcacayaatcatg; 1:N:0:1

@M03670:6:000000000-BCN4V:1:1101:16480:1645_SUB_CMP reverse_score=76.0; status=partial; direction=reverse; tail_quality=38.5; reverse_match=aagggcaccacaagaacgc; seq_length_ori=151; seq_length=122; sample=BI_0_1_1; experiment=eDNA; location=BI_0; mid_quality=38.3893129771; head_quality=34.6; avg_quality=38.1456953642; grab=BI_0_1; reverse_primer=aagggcaccacaagaacgc; 2:N:0:1

Any suggestions?

**Comment by enormandeau** [comment]
if you launch the command with " " at the end, it will tell the script to use a space as a separator. Your name format is a bit strange so possibly you'll need to test some.

**Comment by HXP2016** [comment]
The script from your website works for me when I use "_SUB" as a separator. The new script you sent me by email works when I use either "_SUB" or " " as a separator. Thank you very much for your help!
